class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text,
      this.domain,
      this.by,
      this.age,
      this.score,
      this.commentsCount});
}

final articles = [
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "jonryanedge.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you fuck!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you fuck!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
];

final nipples = [
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you fuck!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you fuck!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
  new Article(
    text: "Title of an article you might be interested in!",
    domain: "ryznler.com",
    by: "jonryanedge",
    age: "1 hour",
    score: 100,
    commentsCount: 77,
  ),
];
